const fs = require('fs');
const path = require('path');

function updateFile(filepath, regex, replacement) {
    if (!fs.existsSync(filepath)) {
        console.log(`File not found: ${filepath}`);
        return;
    }

    const content = fs.readFileSync(filepath, 'utf8');
    const updatedContent = content.replace(regex, replacement);

    if (content !== updatedContent) {
        fs.writeFileSync(filepath, updatedContent, 'utf8');
        console.log(`Updated: ${filepath}`);
    } else {
        console.log(`Up to date: ${filepath}`);
    }
}

function main() {
    const rootDir = path.resolve(__dirname, '..');
    const versionFile = path.join(rootDir, 'version.json');

    let newVersion = null;
    try {
        const data = JSON.parse(fs.readFileSync(versionFile, 'utf8'));
        newVersion = data.version;
    } catch (err) {
        console.error(`Failed to read version.json: ${err.message}`);
        return;
    }

    if (!newVersion) {
        console.error("Error: 'version' key not found in version.json");
        return;
    }

    console.log(`Syncing version ${newVersion} across codebase...`);

    // 1. package.json
    updateFile(
        path.join(rootDir, 'cli', 'package.json'),
        /("version":\s*")[^"]+(")/g,
        `$1${newVersion}$2`
    );

    // 2. raven.js
    updateFile(
        path.join(rootDir, 'cli', 'bin', 'raven.js'),
        /(return\s+")[^"]+(";)/g,
        `$1${newVersion}$2`
    );

    // 3. raven bash script
    updateFile(
        path.join(rootDir, 'raven'),
        /(echo\s+"raven\s+)[^"]+(")/g,
        `$1${newVersion}$2`
    );

    // 4. Cargo.toml (raven-core)
    const cargoPath = path.join(rootDir, 'rust', 'raven-core', 'Cargo.toml');
    if (fs.existsSync(cargoPath)) {
        let content = fs.readFileSync(cargoPath, 'utf8');
        let updatedContent = content.replace(/^(version\s*=\s*")[^"]+(")/m, `$1${newVersion}$2`);
        if (content !== updatedContent) {
            fs.writeFileSync(cargoPath, updatedContent, 'utf8');
            console.log(`Updated: ${cargoPath}`);
        } else {
            console.log(`Up to date: ${cargoPath}`);
        }
    }

    // 5. API_REFERENCE.md
    updateFile(
        path.join(rootDir, 'Docs', 'API_REFERENCE.md'),
        /(static var version: String\s*\/\/\s*")[^"]+(")/g,
        `$1${newVersion}$2`
    );

    // 6. Generate Version.swift
    const swiftVersionDir = path.join(rootDir, 'Sources', 'Raven');
    if (!fs.existsSync(swiftVersionDir)) {
        fs.mkdirSync(swiftVersionDir, { recursive: true });
    }
    const swiftVersionPath = path.join(swiftVersionDir, 'Version.swift');
    const swiftContent = `// AUTO-GENERATED BY scripts/sync_version.js
// DO NOT EDIT MANUALLY

public enum RavenVersion {
    /// The current version of the Raven Framework
    public static let current = "${newVersion}"
}
`;
    fs.writeFileSync(swiftVersionPath, swiftContent, 'utf8');
    console.log(`Generated: ${swiftVersionPath}`);

    console.log("Version sync complete.");
}

main();
