#!/usr/bin/env python3
import json
import os
import re

def update_file(filepath, pattern, replacement):
    if not os.path.exists(filepath):
        print(f"File not found: {filepath}")
        return
        
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
        
    updated_content = re.sub(pattern, replacement, content, flags=re.MULTILINE)
    
    if content != updated_content:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(updated_content)
        print(f"Updated: {filepath}")
    else:
        print(f"Up to date: {filepath}")

def main():
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    version_file = os.path.join(root_dir, 'version.json')
    
    try:
        with open(version_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            new_version = data.get('version')
            if not new_version:
                print("Error: 'version' key not found in version.json")
                return
    except Exception as e:
        print(f"Failed to read version.json: {e}")
        return

    print(f"Syncing version {new_version} across codebase...")

    # 1. package.json
    update_file(
        os.path.join(root_dir, 'cli', 'package.json'),
        r'("version":\s*")[^"]+(")',
        rf'\g<1>{new_version}\g<2>'
    )
    
    # 2. raven.js
    update_file(
        os.path.join(root_dir, 'cli', 'bin', 'raven.js'),
        r'(return\s+")[^"]+(";)',
        rf'\g<1>{new_version}\g<2>'
    )
    
    # 3. raven bash script
    update_file(
        os.path.join(root_dir, 'raven'),
        r'(echo\s+"raven\s+)[^"]+(")',
        rf'\g<1>{new_version}\g<2>'
    )
    
    # 4. Cargo.toml (raven-core)
    # We only want to replace the first occurrence (under [package])
    cargo_path = os.path.join(root_dir, 'rust', 'raven-core', 'Cargo.toml')
    if os.path.exists(cargo_path):
        with open(cargo_path, 'r', encoding='utf-8') as f:
            content = f.read()
        updated_content = re.sub(r'^(version\s*=\s*")[^"]+(")', rf'\g<1>{new_version}\g<2>', content, count=1, flags=re.MULTILINE)
        if content != updated_content:
            with open(cargo_path, 'w', encoding='utf-8') as f:
                f.write(updated_content)
            print(f"Updated: {cargo_path}")
        else:
            print(f"Up to date: {cargo_path}")

    # 5. API_REFERENCE.md
    update_file(
        os.path.join(root_dir, 'Docs', 'API_REFERENCE.md'),
        r'(static var version: String\s*//\s*")[^"]+(")',
        rf'\g<1>{new_version}\g<2>'
    )
    
    # 6. Generate Version.swift
    swift_version_path = os.path.join(root_dir, 'Sources', 'Raven', 'Version.swift')
    swift_content = f"""// AUTO-GENERATED BY scripts/sync_version.py
// DO NOT EDIT MANUALLY

public enum RavenVersion {{
    /// The current version of the Raven Framework
    public static let current = "{new_version}"
}}
"""
    with open(swift_version_path, 'w', encoding='utf-8') as f:
        f.write(swift_content)
    print(f"Generated: {swift_version_path}")
    
    print("Version sync complete.")

if __name__ == '__main__':
    main()
